name: Bug Report
description: Report a bug that is causing a problem.
title: "[Bug:] "
labels: ["status: triage_needed"]
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report! By 
        submitting this issue, you agree to follow our 
        [Code of Conduct](https://noaa-fims.github.io/collaborative_workflow/code-of-conduct.html#code-of-conduct).

        ---

        Before filling out this report please search the existing issues to see
        if the problem has already been reported. If it has, please add a
        comment to the open issue or link to the related, but closed, issue in
        this report.
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: Please provide a description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Describe how to reproduce the bug
      description: |
        Please include a minimal reproducible example (i.e., a
        [reprex]((https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html))).
        If you have not heard of a [reprex](http://reprex.tidyverse.org/)
        before, you can start by reading about them on the [tidyverse
        blog](https://www.tidyverse.org/help/#reprex). Feel free to copy, paste,
        and edit the [demo
        vignette](https://github.com/NOAA-FIMS/FIMS/blob/4539fc4b6e65b901231c4fb66a113bb5b5d54d22/vignettes/fims-demo.Rmd)
        for your reprex.
      placeholder: |
        # insert reprex here
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the bug.
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: Which OS are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Mac
        - Linux
        - Other
    validations: 
      required: false
  - type: dropdown
    id: browser
    attributes:
      label: Which browser are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Which version of FIMS are you seeing the problem on?
      description: |
        You can get the version number of FIMS you are working with from your R
        session using `packageVersion("FIMS")`. If a version number is not
        relevant, perhaps provide a commit hash that is relevant.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here. For example, copy and
        paste the results of `sessionInfo()`, if you are using R, below. Or,
        can you reproduce this issue reliably, and if not, then provide details
        about how often the problem happens and under which conditions it
        normally happens.
    validations:
      required: false
