name: Developer (other issue)
description: |
  This issue form is for developers of FIMS and its associated tools to
  document anything that is not related to a bug or feature.
title: "[Developer Issue]: "
labels: ["status: triage_needed"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue! By 
        submitting this issue, you agree to follow our 
        [Code of Conduct](https://noaa-fims.github.io/collaborative_workflow/code-of-conduct.html#code-of-conduct).

        ---

        Before filling out this report please search the existing issues to see
        if the problem has already been reported. If it has, please add a
        comment to the open issue or link to the related, but closed, issue in
        this report.
  - type: textarea
    id: describe
    attributes:
      label: Description
      description: Please describe the problem.
    validations:
      required: true
      